name: Cypress Tests
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          install-command: npm i --force
      
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          build: npm run build
          start: npm run dev
          wait-on: 'http://localhost:10001'
