name: svelte-starter deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  bun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - run: bun i
      - run: bun run build
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x, 20.x, 21.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run bundle
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x, 20.x, 21.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          install-command: npm i
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          build: npm run build
          start: npm run dev
          wait-on: 'http://localhost:10001'
  deploy:
    runs-on: ubuntu-latest
    needs: [build, cypress-run]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm i
      - run: npm run bundle
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
